global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ifarm-services'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:3000'
          - 'host.docker.internal:3001'
          - 'host.docker.internal:3002'
          - 'host.docker.internal:3003'
          - 'host.docker.internal:3004'
          - 'host.docker.internal:3005'
          - 'host.docker.internal:3006'
          - 'host.docker.internal:3007'
          - 'host.docker.internal:3008'
          - 'host.docker.internal:3009'
          - 'host.docker.internal:3010'
          - 'host.docker.internal:3011'
        labels:
          environment: 'development'
