import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './sections/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#89d89e',
        'surface-tint': '#89d89e',
        'inverse-on-surface': '#2d3133',
        'on-primary-fixed': '#00210d',
        'on-tertiary-fixed-variant': '#792d39',
        'surface-container': '#1d2022',
        'inverse-primary': '#1b6c3d',
        'on-secondary-fixed': '#261a00',
        'secondary-fixed-dim': '#f6be39',
        outline: '#899389',
        'on-secondary': '#402d00',
        'surface-container-highest': '#323537',
        'inverse-surface': '#e0e3e5',
        surface: '#101415',
        'surface-variant': '#323537',
        'on-primary-container': '#9ae9ae',
        'surface-bright': '#363a3b',
        'on-tertiary-container': '#ffcace',
        primary: '#89d89e',
        tertiary: '#ffb2b9',
        'tertiary-fixed-dim': '#ffb2b9',
        'surface-dim': '#101415',
        'secondary-fixed': '#ffdfa0',
        'on-primary-fixed-variant': '#005229',
        'on-tertiary': '#5c1624',
        'on-error': '#690005',
        'primary-container': '#1a6b3c',
        'on-surface': '#e0e3e5',
        'surface-container-lowest': '#0b0f10',
        'secondary-container': '#c59300',
        'on-background': '#e0e3e5',
        'tertiary-container': '#96434f',
        'tertiary-fixed': '#ffd9dc',
        'on-secondary-container': '#433000',
        'error-container': '#93000a',
        background: '#101415',
        'on-primary': '#00391b',
        'surface-container-high': '#272a2c',
        'outline-variant': '#404940',
        error: '#ffb4ab',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#a5f4b8',
        'surface-container-low': '#191c1e',
        'on-tertiary-fixed': '#3f0110',
        'on-secondary-fixed-variant': '#5c4300',
        'on-surface-variant': '#bfc9be',
        secondary: '#f6be39',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
