apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  namespace: ifarm
  labels:
    app: SERVICE_NAME
    platform: ifarm
spec:
  type: ClusterIP
  selector:
    app: SERVICE_NAME
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
